### ISSUE TITLE
Uploading a file is currently broken

### ISSUE THREAD

**Issue by tavalin** [hughc/pixel-art-server#1]
I suspect the recent restructure may have broken some functionality.  I've managed to get the server to run but when trying to upload an image I get the following:

```
ReferenceError: path is not defined
    at uploadFiles (file:///home/tavalin/pixel-art-server/endpoints/upload_files.js:22:19)
    at Layer.handle [as handle_request] (/home/tavalin/pixel-art-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/tavalin/pixel-art-server/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/tavalin/pixel-art-server/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/tavalin/pixel-art-server/node_modules/express/lib/router/layer.js:95:5)
    at /home/tavalin/pixel-art-server/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/tavalin/pixel-art-server/node_modules/express/lib/router/index.js:346:12)
    at next (/home/tavalin/pixel-art-server/node_modules/express/lib/router/index.js:280:10)
    at jsonParser (/home/tavalin/pixel-art-server/node_modules/express/node_modules/body-parser/lib/types/json.js:119:7)
    at Layer.handle [as handle_request] (/home/tavalin/pixel-art-server/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by hughc** [comment]
fixed and retested, should be good now.
